### PR TITLE
only use termImg if not on windows

### PR DESCRIPTION
**Pull request by AndreasWebdev**
calling termImg on windows results in a fatal error. I added the dependency and function call in a platform-dependent if.

### CODE REVIEW

**Comment by torch2424** [comment]
Oh rad! Nice catch :)

**Comment by torch2424** [comment]
If I could ask though, is everything working fine on windows? I only use Windows for my gaming PC, not development :)

**Comment by AndreasWebdev** [comment]
I do have to make some adjustments. For example, the paths of the default config have the ./ that leads to an error

```
PS F:\Development\piStreamRadio> node . gmn


Starting Stream!


(node:13800) UnhandledPromiseRejectionWarning: Error: F:\Development\piStreamRadio/gmn./audio does not exist.
    at Object.notExist (F:\Development\piStreamRadio\node_modules\find\index.js:41:12)
    at traverseSync (F:\Development\piStreamRadio\node_modules\find\index.js:224:38)
    at Object.find.(anonymous function) [as fileSync] (F:\Development\piStreamRadio\node_modules\find\index.js:374:5)
    at extensions.forEach.extension (F:\Development\piStreamRadio\stream\stream.js:21:15)
    at Array.forEach (<anonymous>)
    at getRandomFileWithExtensionFromPath (F:\Development\piStreamRadio\stream\stream.js:18:14)
    at stream (F:\Development\piStreamRadio\stream\stream.js:34:28)
    at module.exports (F:\Development\piStreamRadio\stream\stream.js:179:3)
    at Object.<anonymous> (F:\Development\piStreamRadio\index.js:40:30)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
(node:13800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also, I added ffmpeg binaries to a bin folder in the project and used setFfmpegPath and setFfprobePath in the stream.js because it's much easier than installing it and manually adding ffmpeg to the path

**Comment by torch2424** [comment]
Oh yeah! The loop was broken on that last commit. Took me foreeevveerrr to get the drawtext and video looping working with all the different formats. Just got it all sorted out. Gonna update my current progress on the issues 😄

**Comment by torch2424** [comment]
@AndreasWebdev Did you pull in the latest of the node rebuild branch?

But yeah open a new issue and we can go from there 👍 Maybe it's a windows thing?

Also, just another quick thing to look into, you have to compile ffmpeg using `--enable-libfreetype`. That is required to get the text on video unfortunately 😢

**Comment by torch2424** [comment]
Looks like you already have libfreetype, yeah just post the logs in a new issue haha!

**Pull request merged**
