### PR TITLE
change the shebangs

### PR DESCRIPTION
**Pull request by karimamer**

### CODE REVIEW

**Comment by torch2424** [comment]
Is this good to go? Or can you provide more context on this? Thanks for the PR! 😄

**Comment by karimamer** [comment]
oops here is where I found this.
 https://stackoverflow.com/questions/20615217/bash-bad-substitution

**Comment by karimamer** [comment]
this is good to go

**Comment by torch2424** [comment]
Rad thanks!

Sorry I just saw this I'm totally derping haha :')

**Pull request merged**
